### ISSUE TITLE
Rubycritic not running!

### ISSUE THREAD

**Issue by OfficeYAportatil** [whitesmith/rubycritic#388] opened 2021-03-02 19:26 UTC
I've been wearing your fantastic gem for a long time. But I am getting the following errors in a new app I am writing:

`	31: from /home/addicttux/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
	30: from /home/addicttux/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `eval'
	29: from /home/addicttux/.rvm/gems/ruby-2.7.2/bin/rubycritic:23:in `<main>'
	28: from /home/addicttux/.rvm/gems/ruby-2.7.2/bin/rubycritic:23:in `load'
	27: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/rubycritic-0.0.14/bin/rubycritic:3:in `<top (required)>'
	26: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/rubycritic-0.0.14/bin/rubycritic:3:in `require'
	25: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/rubycritic-0.0.14/lib/rubycritic/cli.rb:5:in `<top (required)>'
	24: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/rubycritic-0.0.14/lib/rubycritic/cli.rb:27:in `<module:Rubycritic>'
	23: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/rubycritic-0.0.14/lib/rubycritic/orchestrators/base.rb:11:in `critique'
	22: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/rubycritic-0.0.14/lib/rubycritic/analysers_runner.rb:18:in `smells'
	21: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/rubycritic-0.0.14/lib/rubycritic/analysers_runner.rb:24:in `smell_adapters'
	20: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/rubycritic-0.0.14/lib/rubycritic/analysers_runner.rb:24:in `map'
	19: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/rubycritic-0.0.14/lib/rubycritic/analysers_runner.rb:25:in `block in smell_adapters'
	18: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/rubycritic-0.0.14/lib/rubycritic/analysers_runner.rb:25:in `new'
	17: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/rubycritic-0.0.14/lib/rubycritic/adapters/smell/reek.rb:9:in `initialize'
	16: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/rubycritic-0.0.14/lib/rubycritic/adapters/smell/reek.rb:9:in `new'
	15: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/rubycritic-0.0.14/lib/rubycritic/analysers/reek.rb:10:in `initialize'
	14: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/examiner.rb:34:in `initialize'
	13: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/source/source_repository.rb:29:in `each'
	12: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/source/source_repository.rb:29:in `each'
	11: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/examiner.rb:34:in `block in initialize'
	10: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/sniffer.rb:27:in `report_on'
	 9: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:23:in `process'
	 8: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:34:in `process_module'
	 7: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:161:in `push'
	 6: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/core/code_parser.rb:35:in `block in process_module'
	 5: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/sexp_processor-4.15.2/lib/sexp.rb:248:in `method_missing'
	 4: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/sexp_processor-4.15.2/lib/sexp.rb:192:in `find_node'
	 3: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/sexp_processor-4.15.2/lib/sexp.rb:210:in `find_nodes'
	 2: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/source/sexp_node.rb:38:in `each_sexp'
	 1: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/source/sexp_node.rb:38:in `each'
/home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/source/sexp_node.rb:38:in `block in each_sexp': no block given (yield) (LocalJumpError)
`

I got those messages when running: 
`$ rubycritic`

For this new project, I am using:
Rails 6.1.3
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
rvm 1.29.12 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
node v14.16.0
gem 3.1.4

My Gemfile is:

`source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

gem 'bcrypt', '~> 3.1.16'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'coffee-script'
gem 'devise'
gem 'haml'
gem 'jbuilder', '~> 2.7'
gem 'puma', '~> 5.0'
gem 'rails', '~> 6.1.3'
gem 'sass-rails', '>= 6'
gem 'sqlite3', '~> 1.4'
gem 'turbolinks', '~> 5'
gem 'webpacker', '~> 5.0'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'guard'
  gem 'guard-minitest'
end

group :development do
  gem 'brakeman'
  gem 'consistency_fail'
  gem 'flog'
  gem 'fly'
  gem 'guard-annotate'
  gem 'guard-brakeman'
  gem 'guard-bundler', require: false
  gem 'guard-coffeelint' # coffeelint --makeconfig > coffeelint.json
  gem 'guard-consistency_fail' # falla el init
  gem 'guard-haml_lint'
  gem 'guard-livereload', '~> 2.5', require: false
  gem 'guard-migrate'
  gem 'guard-puma'
  gem 'guard-railsbp'
  gem 'guard-reek'
  gem 'guard-rubocop'
  gem 'guard-rubycritic'
  gem 'guard-shell'
  gem 'listen', '~> 3.3'
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'rails_best_practices'
  gem 'reek', require: false
  gem 'rubocop', require: false
  gem 'rubocop-i18n'
  gem 'rubocop-minitest', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubycritic', require: false
  gem 'spring'
  gem 'web-console', '>= 4.1.0'
end

group :test do
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end
`

**Comment by etagwerker** [comment] 2021-03-02 19:59
@OfficeYAportatil It seems that you have cut off the error message. Could you please include it in your description?

**Comment by etagwerker** [comment] 2021-03-04 18:15
Closing as I can't reproduce with more info. Feel free to reopen later.

**Closed by etagwerker** 2021-03-04 18:15 UTC

**Comment by OfficeYAportatil** [comment] 2021-03-04 23:47
Hi I see that I didn't copy the first line of the error, it is:

`	 1: from /home/addicttux/.rvm/gems/ruby-2.7.2/gems/reek-1.3.6/lib/reek/source/sexp_node.rb:38:in `each'
`

**Comment by OfficeYAportatil** [comment] 2021-03-04 23:57
@etagwerker , it seems that the error is produced by reek. I just run it in my command line, and I get the same errors about `sexp_node (sexp_processor)`

Thanks for your attention and time

**Comment by etagwerker** [comment] 2021-03-05 15:49
@OfficeYAportatil it seems that you are using quite an old version of reek? You might want to bump that dependency as 6.0.x is the current version: https://rubygems.org/gems/reek/versions
